from typing import List

import numpy as np

# Generated by Qodo Gen
import pytest
from hypothesis import given
from hypothesis import strategies as st
from hypothesis.extra.numpy import arrays

from pybandits.base import BinaryReward
from pybandits.model import Beta
from pybandits.quantitative_model import CmabZoomingModel, Segment, SmabZoomingModel, ZoomingModel


def tuple_of_tuples_strategy(n, m, elements=st.floats(min_value=0, max_value=1)):
    return st.tuples(*[st.tuples(*[elements for _ in range(m)]) for _ in range(n)])


# Create segment with valid intervals array of shape (n,2)
@given(tuple_of_tuples_strategy(2, 2))
def test_create_valid_segment(intervals):
    segment = Segment(intervals=intervals)
    assert isinstance(segment, Segment)
    assert len(segment.intervals) == 2
    assert all(len(interval) == 2 for interval in segment.intervals)


# Access minimum and maximum quantities via mins and maxs properties
@given(tuple_of_tuples_strategy(3, 2))
def test_mins_maxs_properties(intervals):
    segment = Segment(intervals=intervals)
    assert np.all(segment.mins == np.array([interval[0] for interval in intervals]))
    assert np.all(segment.maxs == np.array([interval[1] for interval in intervals]))


# Create segment with empty intervals array
def test_create_empty_segment():
    empty_intervals = np.empty((0, 2))
    segment = Segment(intervals=empty_intervals)
    assert len(segment.intervals) == 0
    assert len(segment.mins) == 0
    assert len(segment.maxs) == 0


# Create segment with invalid interval shape
@given(arrays(np.float64, shape=(2, 3), elements=st.floats(min_value=0, max_value=100)))
def test_invalid_interval_shape(intervals):
    with pytest.raises(ValueError, match="Intervals must have shape .n, 2."):
        Segment(intervals=intervals)


# Add non-adjacent segments
def test_add_nonadjacent_segments():
    seg1 = Segment(intervals=np.array([[0, 0.1], [0, 0.1]]))
    seg2 = Segment(intervals=np.array([[0.2, 0.5], [0.1, 0.2]]))
    with pytest.raises(ValueError, match="Segments must be adjacent."):
        seg1 + seg2


class DummyZoomingModel(ZoomingModel):
    def _init_base_model(self):
        self._base_model = Beta()

    def _inner_update(self, segments: List[Segment], rewards: List[BinaryReward], **kwargs):
        pass


# Model initialization with valid parameters creates correct number of segments
@given(dimension=st.integers(min_value=1, max_value=3), n_1d_segments=st.integers(min_value=2, max_value=8))
def test_init_creates_correct_segments(dimension, n_1d_segments):
    model = DummyZoomingModel.cold_start(dimension=dimension, n_1d_segments=n_1d_segments, n_max_segments=None)
    expected_segments = n_1d_segments**dimension
    assert len(model.sub_actions) == expected_segments


# Update method correctly processes rewards and quantities for existing segments
@given(
    st.integers(min_value=1, max_value=5).flatmap(
        lambda size: st.tuples(
            st.lists(st.integers(min_value=0, max_value=1), min_size=size, max_size=size),
            st.lists(st.floats(min_value=0, max_value=1), min_size=size, max_size=size),
        )
    )
)
def test_update_processes_rewards_correctly(data):
    rewards, quantities = data
    model = DummyZoomingModel.cold_start(dimension=1, n_1d_segments=4)
    initial_segments = len(model.sub_actions)
    model.update(quantities=quantities, rewards=rewards)
    assert len(model.sub_actions) <= initial_segments


# Best performing segment gets split when below max segments limit
def test_best_segment_splits():
    model = DummyZoomingModel.cold_start(dimension=1, n_1d_segments=2, n_max_segments=4)
    quantities = [0.25, 0.75]
    rewards = [1, 0]
    model.update(quantities=quantities, rewards=rewards)
    assert len(model.sub_actions) == 3


# Adjacent segments with similar performance get merged correctly
def test_similar_segments_merge():
    model = DummyZoomingModel.cold_start(dimension=1, n_1d_segments=4, comparison_threshold=0.5)
    initial_segmented_actions = model.sub_actions.copy()
    quantities = [0.25, 0.75]
    rewards = [1, 1]
    model.update(quantities=quantities, rewards=rewards)
    assert initial_segmented_actions.keys() != model.sub_actions
    assert len(model.sub_actions) == 4


# Sample_proba returns valid probability for each segment
def test_sample_proba_returns_valid_probabilities(n_samples=100):
    model = DummyZoomingModel.cold_start(dimension=1, n_1d_segments=2)
    probs = model.sample_proba(n_samples=n_samples)
    assert all(len(prob) == len(model.sub_actions) for prob in probs)
    assert len(probs) == n_samples
    assert all(0 <= prob[1] <= 1 for sample in probs for prob in sample)
    assert all(0 <= v <= 1 for sample in probs for prob in sample for v in prob[0])


# Update with empty rewards/quantities list
def test_update_with_empty_lists():
    model = DummyZoomingModel.cold_start(dimension=1, n_1d_segments=2)
    initial_segments = len(model.sub_actions)
    model.update(quantities=[], rewards=[])
    assert len(model.sub_actions) == initial_segments


# Update when at maximum number of segments
def test_update_at_max_segments():
    model = DummyZoomingModel.cold_start(dimension=1, n_1d_segments=4, n_max_segments=4)
    quantities = [0.5]
    rewards = [1]
    model.update(quantities=quantities, rewards=rewards)
    assert len(model.sub_actions) <= model.n_max_segments


# Merging segments when only 2 segments remain
def test_merge_with_two_segments():
    model = DummyZoomingModel.cold_start(dimension=1, n_1d_segments=2, comparison_threshold=1.0)
    quantities = [0.25, 0.75]
    rewards = [1, 1]
    model.update(quantities=quantities, rewards=rewards)
    assert len(model.sub_actions) >= 1


# Comparing non-adjacent segments for merging
def test_non_adjacent_segments_comparison():
    model = DummyZoomingModel.cold_start(dimension=1, n_1d_segments=4)
    segments = list(model.segmented_actions.keys())
    non_adjacent = [segments[0], segments[2]]
    assert not non_adjacent[0].is_adjacent(non_adjacent[1])


# Values that fall on segment boundaries
@given(st.integers(min_value=2, max_value=4))
def test_boundary_values(n_segments):
    model = DummyZoomingModel.cold_start(dimension=1, n_1d_segments=n_segments)
    boundary = 1.0 / n_segments
    quantities = [boundary]
    rewards = [1]
    model.update(quantities=quantities, rewards=rewards)
    mapped_segments = model._map_values_to_segments(quantities)
    assert len(mapped_segments) >= 1


# Test SmabZoomingModel initialization with valid parameters
@given(dimension=st.integers(min_value=1, max_value=3), n_1d_segments=st.integers(min_value=2, max_value=8))
def initializes_smab_zooming_model_correctly(dimension, n_1d_segments):
    model = SmabZoomingModel(dimension=dimension, n_1d_segments=n_1d_segments)
    expected_segments = n_1d_segments**dimension
    assert len(model.segmented_actions) == expected_segments


# Test SmabZoomingModel update with valid rewards and quantities
@given(
    rewards=st.lists(st.integers(min_value=0, max_value=1), min_size=1, max_size=5),
    quantities=st.lists(st.floats(min_value=0, max_value=1), min_size=1, max_size=5),
)
def updates_smab_zooming_model_correctly(rewards, quantities):
    model = SmabZoomingModel(dimension=1, n_1d_segments=4)
    initial_segments = len(model.segmented_actions)
    model.update(quantities=quantities, rewards=rewards)
    assert len(model.segmented_actions) <= initial_segments


# Test SmabZoomingModel sample_proba returns valid probabilities
def sample_proba_returns_valid_probabilities_smab():
    model = SmabZoomingModel(dimension=1, n_1d_segments=2)
    probas = model.sample_proba()
    for value, prob in probas.items():
        assert 0 <= prob <= 1
        assert 0 <= value <= 1


# Test CmabZoomingModel initialization with valid parameters
@given(dimension=st.integers(min_value=1, max_value=3), n_1d_segments=st.integers(min_value=2, max_value=8))
def initializes_cmab_zooming_model_correctly(dimension, n_1d_segments):
    model = CmabZoomingModel(
        dimension=dimension, n_1d_segments=n_1d_segments, base_model_cold_start_kwargs={"n_features": 1}
    )
    expected_segments = n_1d_segments**dimension
    assert len(model.segmented_actions) == expected_segments


# Test CmabZoomingModel update with valid rewards, quantities, and context
@given(
    rewards=st.lists(st.integers(min_value=0, max_value=1), min_size=1, max_size=5),
    quantities=st.lists(st.floats(min_value=0, max_value=1), min_size=1, max_size=5),
    context=arrays(np.float64, shape=(5, 1), elements=st.floats(min_value=0, max_value=1)),
)
def updates_cmab_zooming_model_correctly(rewards, quantities, context):
    model = CmabZoomingModel(dimension=1, n_1d_segments=4, base_model_cold_start_kwargs={"n_features": 1})
    initial_segments = len(model.segmented_actions)
    model.update(quantities=quantities, rewards=rewards, context=context)
    assert len(model.segmented_actions) <= initial_segments


# Test CmabZoomingModel sample_proba returns valid probabilities
def sample_proba_returns_valid_probabilities_cmab():
    model = CmabZoomingModel(dimension=1, n_1d_segments=2, base_model_cold_start_kwargs={"n_features": 1})
    probas = model.sample_proba()
    for value, prob in probas.items():
        assert 0 <= prob <= 1
        assert 0 <= value <= 1
